site_name: Galaksio Documentation
pages:
- ['index.md', 'Home']
- ['0_install.md', 'Install', 'Installing Galaksio']
- ['1_1_galaxy.md', 'Getting start', 'The Galaxy project and Galaksio']
- ['1_2_concepts.md', 'Getting start', 'Must know concepts']
- ['2_1_users.md', 'User system', 'Users in Galaksio']
- ['3_1_histories.md', 'Histories and datasets', 'Browsing data']
- ['4_1_workflows.md', 'Workflows', 'Browsing workflows']
- ['4_2_workflows.md', 'Workflows', 'Running a workflow']
- ['5_license.md', 'About', 'License']
theme: readthedocs
